name:
  first: ""
  middle: ""
  last: ""
contact:
  email: ""
  phone: ""
  linkedin: ""
  github: ""
  website: ""
address:
  city: ""
  state: ""
  zipcode: ""
  country: ""
demographics:
  gender: ""
  ethnicity: ""
  veteran_status: ""
  disability_status: ""
work_authorization:
  us: ""
  eu: ""
  uk: ""
  canada: ""
  requires_sponsorship: ""
